---
# cofigure ansible engine and nodes with users and access

- hosts: all
  become: true

  vars:

  tasks:
    - name: Set Hostname
      hostname:
        name: "{{ inventory_hostname }}"

    #- name: Configure sshd
    #  lineinfile:
    #    path: "/etc/ssh/sshd_config"
    #    regex: "^(#)?PasswordAuthentication"
    #    line: "PasswordAuthentication yes"
    #    state: present
#
    #- name: Restart sshd
    #  service:
    #    name: sshd
    #    state: restarted

    #- name: Create devops user
    #  user:
    #    name: devops
    #    password: "{{ 'devops' | password_hash('sha512') }}"
    #    state: present
#
    #- name: Enable sudo access for devops user
    #  copy:
    #    content: "devops ALL=(ALL) NOPASSWD: ALL"
    #    dest: /etc/sudoers.d/devops
#

    #- name: Copy Sample Inventory to Vagrant user home
    #  copy:
    #    src: '/vagrant/files/sample-inventory'
    #    dest: "/home/{{ remote_user_name }}/inventory"
    #    mode: '0755'
    #  when: inventory_hostname == 'ansible-engine-1'

    - name: Install Packages
      yum:
        name:
          - git
          - vim
        state: present